### ISSUE TITLE
Unstable Fitting

### ISSUE THREAD

**Issue by wangmiaowei** [threedle/TextDeformer#2]
<img width="480" alt="企业微信截图_015a68db-d319-4f9f-a8ce-86e0cb8ee2c9" src="https://user-images.githubusercontent.com/27915265/236601154-892028c6-a42f-40ac-9d19-cc7d3390116f.png">
Could you give me some suggestions that why there are NaN losses in the fitting procedure.

**Comment by ChocolateBiscuit** [comment]
This seems quite odd, I usually never run into nan losses. To help debug, can you tell me the mesh you are running on (one of ours provided or your own?), the configs you are running on, and which loss specifically is turning into nan (you can check in the tensorboard logs)?

**Comment by ChocolateBiscuit** [comment]
It seems like this may be caused by a bug which I have fixed [here](https://github.com/threedle/TextDeformer/commit/1fafaa9d13e31187010a83b01b0ce2b849c0e6b3), please merge this commit and try again.

**Comment by ChocolateBiscuit** [comment]
I am not sure why you are receiving NaNs, I have rerun a few of my examples and I do not see NaNs. To help debug can you provide the following:
- the mesh you are using (one of ours or your own?)
- the config file
- which loss is becoming NaN (you can check from tensorboard)

**Comment by wangmiaowei** [comment]
Sorry for the late reply. I use my mesh and update the config file. What you need are pasted here:
1. Only Consistency Loss gets NaN value
<img width="489" alt="企业微信截图_310fb524-2a6d-436e-b4fe-df6e16c6de1a" src="https://user-images.githubusercontent.com/27915265/236614283-1eee6103-ae9c-421d-b15a-8d07c314094d.png">
2. My input mesh is pasted here(as .zip file):
[muskV2.obj.zip](https://github.com/threedle/TextDeformer/files/11411928/muskV2.obj.zip)
3. My config file is shown here:
```
output_path: ./all_outputs/trumpV1
gpu: 0
seed: 99

# CLIP-related
text_prompt: Donald Trump
base_text_prompt: Elon Musk
clip_model: ViT-B/32
consistency_clip_model: ViT-B/32
consistency_vit_stride: 8
consistency_vit_layer: 11

# Mesh
mesh: ./meshes/muskV2.obj
retriangulate: 0

# Render settings
bsdf: diffuse

# Hyper-parameters
lr: 0.0025
epochs: 2500
clip_weight: 1.0
delta_clip_weight: 1.0
regularize_jacobians_weight: 0.5
consistency_loss_weight: 0.5
consistency_elev_filter: 30
consistency_azim_filter: 20
batch_size: 5
train_res: 1024
resize_method: cubic

# Camera parameters
fov_min: 30.0
fov_max: 90.0
dist_min: 2.5
dist_max: 3.5
light_power: 5.0
elev_alpha: 1.0
elev_beta: 5.0 
elev_max: 60.0
azim_min: 0.0
azim_max: 360.0
aug_loc: 1
aug_light: 1
aug_bkg: 1
adapt_dist: 1

log_interval: 5
log_interval_im: 150
log_elev: 30.0
log_fov: 60.0
log_dist: 3.0
log_res: 512
log_light_power: 3.0
```

**Comment by ChocolateBiscuit** [comment]
How our consistency loss is implemented is that it maps each visible vertex to a pixel in the 224x224 images passed to CLIP. Visibility is computed by the nvdiffrast rasterizer. Then, it compares corresponding visible vertices in different batches.

I took a look at your configuration. Because your mesh has 100k+ vertices, when rendering to a low resolution like 224x224, there will be a ton of occlusions calculated by our method. Since your batch size is relatively small (5), due to these occlusions, even though it may look like shared vertices are being rendered between the batched views, the actual calculated visible vertices may be slightly different between each of the views. Our method also filters view-pairs based on how close their viewing angles are. Due to your batch size, it may be the case that _all_ pairs are filtered out. When the loss is `nan`, it means that our method did not find any shared vertices between the unfiltered view-pairs.

There are a few ways you can address this, in my recommendation order -- you may try increasing the batch size, if your GPU memory permits. To enable this, you could try parallelizing our method over multiple GPUs. Increasing the batch size may also generally improve your results. You can also increase the permissible difference between viewing angles (the `consistency_elev_filter` and `consistency_azim_filter` parameters). You may also try simplifying the input mesh (our face results came from a mesh with only around 10k vertices). Alternatively, you may ignore these `nan`s since no gradients are passed (the `nan` results from the mean of an empty tensor).
